name: frontend-development
description: Frontend-only implementation (uses existing API) with T1/T2 switching
trigger: internal
called_by: task-orchestrator

parameters:
  - name: task
    type: object
    required: true
  - name: iteration
    type: integer
    default: 1
  - name: tier
    type: string
    default: "t1"
  - name: previous_gaps
    type: array
    default: []

steps:
  - name: load_api_contract
    action: read_file
    file: "docs/api/{existing_api_spec}.yaml"
    note: "Frontend implements against existing API"

  - name: design
    agent: frontend-designer
    action: design_components
    input:
      task: "{task}"
      api_contract: "{api_spec}"
    output: "docs/frontend/{task.id}-design.md"
    skip_if: iteration > 1

  - name: implement
    agent: frontend-developer-{tier}
    action: implement_components
    input:
      design: "docs/frontend/{task.id}-design.md"
      api_contract: "{api_spec}"
    output: "src/frontend/components/"
    tier_selection:
      iteration_1: t1
      iteration_2: t1
      iteration_3_plus: t2

  - name: review
    agent: frontend-code-reviewer
    action: review_code
    input:
      code: "src/frontend/"
      task: "{task}"

  - name: test
    agent: test-writer
    action: write_frontend_tests
    input:
      components: "src/frontend/components/"
      task: "{task}"
    output: "tests/frontend/"

  - name: documentation
    agent: documentation-coordinator
    action: document_components
    input:
      components: "src/frontend/components/"
      task: "{task}"
    output: "docs/components/{task.id}.md"

output:
  artifacts:
    frontend_implementation: "src/frontend/"
    tests: "tests/frontend/"
    documentation: "docs/components/"
  
  metrics:
    tier_used: "{tier}"
