name: sprint-execution
description: Orchestrates entire sprint from start to finish
trigger: manual
command: "/sprint execute {sprint_id}"

parameters:
  - name: sprint_id
    type: string
    required: true
    pattern: "SPRINT-\\d{3}"

steps:
  - name: initialize_sprint
    agent: sprint-orchestrator
    action: read_sprint_file
    input:
      file: "docs/sprints/{sprint_id}.yaml"

  - name: create_execution_log
    agent: sprint-orchestrator
    action: initialize_logging
    output:
      file: "docs/sprints/{sprint_id}-execution.log"
      status_file: "docs/sprints/{sprint_id}-status.md"

  - name: analyze_task_groups
    agent: sprint-orchestrator
    action: build_execution_order
    process:
      - extract task_order from sprint file
      - identify parallel_groups
      - identify sequential dependencies

  - name: execute_task_groups
    agent: sprint-orchestrator
    action: iterate_groups
    for_each: task_group
    parallel: if group is parallel_group
    sequential: if group is sequential
    
    task_execution:
      workflow: task-execution
      parameters:
        task_id: "{task_id}"
        sprint_id: "{sprint_id}"
      
      on_success:
        - mark_complete
        - log_completion
        - update_status_file
        - record_tier_usage
      
      on_failure:
        - log_failure
        - check_blocking_impact
        - notify_human

  - name: validate_sprint_completion
    agent: sprint-orchestrator
    action: check_all_tasks
    validations:
      - all_tasks_complete: true
      - all_deliverables_achieved: true
      - all_quality_gates_passed: true

  - name: generate_sprint_summary
    agent: sprint-orchestrator
    action: create_summary
    output:
      file: "docs/sprints/{sprint_id}-summary.md"
    include:
      - task_performance
      - iteration_statistics
      - tier_usage_statistics
      - quality_metrics
      - lessons_learned
      - next_sprint_readiness

  - name: notify_completion
    action: message
    content: |
      ✓ {sprint_id} complete!
      
      Summary:
      - {task_count}/{task_count} tasks completed
      - Total iterations: {iteration_count}
      - T1→T2 switches: {tier_switch_count}
      - All deliverables achieved
      
      Full report: docs/sprints/{sprint_id}-summary.md
      
      Next: `/sprint execute {next_sprint_id}`

completion:
  status: "Sprint complete"
  next_action: "Start next sprint or review backlog"

error_handling:
  task_failure:
    - pause_sprint
    - generate_failure_report
    - request_human_intervention
    - options:
        - retry_with_guidance
        - skip_task_with_debt
        - adjust_requirements
